#Sites
title: [Git for Beginner Maintainers]
home-page: "https://hoytpr.github.io/git_beginner/"
favicon.ico: "https://hoytpr.github.io/git_beginner/img/favicon.ico"
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end